# Generates test content for Products.
---
# Nodes for the Product bundle.
- entity: "node"
  type: "product"
  title: "Echo Show"
  status: 1
  uid: 1
  field_summary:
    - value: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, turpis at luctus finibus, erat lectus convallis velit, at sodales purus lacus quis magna. Curabitur imperdiet sapien libero, fringilla ullamcorper nibh ullamcorper vitae. Proin sed luctus augue.
  field_thumbnail:
    - entity: media
      bundle: image
      name: 'Product 1'
      status: 1
      field_image:
        - '#process':
            callback: 'file'
            args:
              - 'image'
              - type: 'module'
                filename: 'echo-thumb.jpg'
            alt: 'product1'
  field_product_media:
    - entity: media
      bundle: image
      name: 'Product 1'
      status: 1
      field_image:
        - '#process':
            callback: 'file'
            args:
              - 'image'
              - type: 'module'
                filename: 'blue.jpg'
            alt: 'product1'
    - entity: media
      bundle: image
      name: 'Product 1b'
      status: 1
      field_image:
        - '#process':
            callback: 'file'
            args:
              - 'image'
              - type: 'module'
                filename: 'blue.jpg'
            alt: 'product1b'
    - entity: media
      bundle: image
      name: 'Product 1c'
      status: 1
      field_image:
        - '#process':
            callback: 'file'
            args:
              - 'image'
              - type: 'module'
                filename: 'blue.jpg'
            alt: 'product1c'
  field_product_desc:
    - format: "full_html"
      summary: ''
      value: |
        <ul>
        <li>Echo Show brings you everything you love about Alexa, and now she can show you things. Watch video flash briefings, Amazon Video content, and YouTube, see music lyrics, security cameras, photos, weather forecasts, to-do and shopping lists, browse and listen to Audible audiobooks, and more. All hands-free—just ask.</li>
        <li>Introducing a new way to be together. Make hands-free video calls to friends and family who have an Echo Show or the Alexa App, and make voice calls to anyone who has an Echo or Echo Dot.</li>
        <li>See lyrics on-screen with Amazon Music. Just ask to play a song, artist or genre, and stream over Wi-Fi. Also, stream music on Pandora, Spotify, TuneIn, iHeartRadio, and more.</li>
        <li>Powerful, room-filling speakers with Dolby processing for crisp vocals and extended bass response. Play your music simultaneously across Echo devices with multi-room music (Spotify and Sirius XM support coming soon, Bluetooth not supported).</li>
        <li>Ask Alexa to show you the front door or monitor the baby's room with compatible cameras from Ring and Arlo. Turn on lights or the TV, set thermostats, control Amazon Video on Fire TV, and more with WeMo, Philips Hue, Sony, ecobee, and other compatible smart home devices.</li>
        <li>With eight microphones, beam-forming technology, and noise cancellation, Echo Show hears you from any direction—even while music is playing</li>
        <li>Always getting smarter and adding new features, plus thousands of skills like Uber, Allrecipes, CNN, and more</li>
        </ul>
  field_link:
    - uri: 'http://google.com/'
      title: 'Request quote'
  field_content:
    - entity: paragraph
      type: text
      field_body:
        - format: "full_html"
          summary: ''
          value: |
            <p>Voice responses from Alexa are now enhanced with visuals and optimized for visibility across the room. Call or message your family and friends that also have an Echo or the Alexa App, get the news with a video flash briefing, see your Prime Photos, shop with your voice, see lyrics with Amazon Music, browse and listen to Audible audiobooks, and more. All you have to do is ask.</p>
            <p>Echo Show has eight microphones and beam-forming technology so it can hear you from across the room—even while music is playing. Echo Show is also an expertly tuned speaker that can fill any room with immersive audio powered by Dolby. When you want to use Echo Show, just say the wake word “Alexa” and Echo Show responds instantly.</p>
    - entity: paragraph
      type: media
      field_media:
        - entity: media
          bundle: image
          name: 'Echo'
          status: 1
          field_image:
            - '#process':
                callback: 'file'
                args:
                  - 'image'
                  - type: 'module'
                    filename: 'echo-image.jpg'
                alt: 'Echo'
    - entity: paragraph
      type: text
      field_body:
        - format: "full_html"
          summary: ''
          value: |
            <p>Maecenas rhoncus, mi varius interdum euismod, odio velit bibendum libero, et cursus lectus sem quis sem. Quisque eget mauris accumsan, sollicitudin turpis at, mollis tellus. Vivamus scelerisque mauris eget enim dapibus fringilla. Aliquam erat volutpat. Aenean tincidunt scelerisque tortor vitae pellentesque.</p>
    - entity: paragraph
      type: media
      field_media:
        - entity: media
          bundle: video
          name: 'Amazon Echo Show'
          status: 1
          field_media_video_embed_field:
            - value: 'https://www.youtube.com/watch?v=WQqxCeHhmeU'
    - entity: paragraph
      type: text
      field_body:
        - format: "full_html"
          summary: ''
          value: |
            <p>For news and information you can see and hear, just ask Alexa for your video flash briefing from CNN, Bloomberg, and more. Curious about the latest movie trailers or a need a how-to video from YouTube? Just ask.</p>
    - entity: paragraph
      type: view
      field_view_ref:
        - target_id: 'related_products'
          display_id: 'block_1'
          title: 1
- entity: "node"
  type: "product"
  title: "Apple iPhone 7 Plus"
  status: 1
  uid: 1
  field_summary:
    - value: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, turpis at luctus finibus, erat lectus convallis velit, at sodales purus lacus quis magna. Curabitur imperdiet sapien libero, fringilla ullamcorper nibh ullamcorper vitae. Proin sed luctus augue.
  field_thumbnail:
    - entity: media
      bundle: image
      name: 'Product 2'
      status: 1
      field_image:
        - '#process':
            callback: 'file'
            args:
              - 'image'
              - type: 'module'
                filename: 'iphone-thumb.jpg'
            alt: 'product2'
  field_product_media:
    - entity: media
      bundle: image
      name: 'Product 2'
      status: 1
      field_image:
        - '#process':
            callback: 'file'
            args:
              - 'image'
              - type: 'module'
                filename: 'blue.jpg'
            alt: 'product2'
    - entity: media
      bundle: image
      name: 'Product 2b'
      status: 1
      field_image:
        - '#process':
            callback: 'file'
            args:
              - 'image'
              - type: 'module'
                filename: 'blue.jpg'
            alt: 'product2b'
    - entity: media
      bundle: image
      name: 'Product 2c'
      status: 1
      field_image:
        - '#process':
            callback: 'file'
            args:
              - 'image'
              - type: 'module'
                filename: 'blue.jpg'
            alt: 'product2c'
  field_product_desc:
    - format: "full_html"
      summary: ''
      value: |
        <ul>
        <li>Keep everything you love about iPhone up to date, secure, and accessible from any device with iCloud</li>
        <li>Multi-Touch display with IPS technology</li>
        <li>With just a single press, 3D Touch lets you do more than ever before</li>
        <li>The 12-megapixel iSight camera captures sharp, detailed photos. It takes 4K video, up to four times the resolution of 1080p HD video</li>
        <li>This is an International Version of the phone (A1784) that comes with no warranty in the US and will work on GSM carriers globally, but not CDMA Sim Cards.</li>
        </ul>
  field_link:
    - uri: 'http://google.com/'
      title: 'Contact us'
  field_content:
    - entity: paragraph
      type: text
      field_body:
        - format: "full_html"
          summary: ''
          value: |
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, turpis at luctus finibus, erat lectus convallis velit, at sodales purus lacus quis magna. Curabitur imperdiet sapien libero, fringilla ullamcorper nibh ullamcorper vitae. Proin sed luctus augue. Nam fringilla enim leo, non sodales ante gravida ac.</p>
            <p>Maecenas rhoncus, mi varius interdum euismod, odio velit bibendum libero, et cursus lectus sem quis sem. Quisque eget mauris accumsan, sollicitudin turpis at, mollis tellus. Vivamus scelerisque mauris eget enim dapibus fringilla. Aliquam erat volutpat. Aenean tincidunt scelerisque tortor vitae pellentesque. Suspendisse imperdiet suscipit arcu, vel posuere mauris fermentum at. Suspendisse potenti. Sed at fermentum odio. Aliquam condimentum consectetur eleifend. Nullam mollis ac tellus sit amet convallis. Donec consectetur pretium sapien a dictum. Aliquam ut erat ac nibh tempor interdum ac ut nisi.</p>
    - entity: paragraph
      type: media
      field_media:
        - entity: media
          bundle: video
          name: 'iPhone 7'
          status: 1
          field_media_video_embed_field:
            - value: 'https://www.youtube.com/watch?v=Q6dsRpVyyWs'
    - entity: paragraph
      type: text
      field_body:
        - format: "full_html"
          summary: ''
          value: |
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, turpis at luctus finibus, erat lectus convallis velit, at sodales purus lacus quis magna. Curabitur imperdiet sapien libero, fringilla ullamcorper nibh ullamcorper vitae. Proin sed luctus augue. Nam fringilla enim leo, non sodales ante gravida ac.</p>
            <p>Maecenas rhoncus, mi varius interdum euismod, odio velit bibendum libero, et cursus lectus sem quis sem. Quisque eget mauris accumsan, sollicitudin turpis at, mollis tellus. Vivamus scelerisque mauris eget enim dapibus fringilla. Aliquam erat volutpat. Aenean tincidunt scelerisque tortor vitae pellentesque. Suspendisse imperdiet suscipit arcu, vel posuere mauris fermentum at. Suspendisse potenti. Sed at fermentum odio. Aliquam condimentum consectetur eleifend. Nullam mollis ac tellus sit amet convallis. Donec consectetur pretium sapien a dictum. Aliquam ut erat ac nibh tempor interdum ac ut nisi.</p>
    - entity: paragraph
      type: view
      field_view_ref:
        - target_id: 'related_products'
          display_id: 'block_1'
          title: 1
- entity: "node"
  type: "product"
  title: "Point of Sales (POS)"
  status: 1
  uid: 1
  field_summary:
    - value: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, turpis at luctus finibus, erat lectus convallis velit, at sodales purus lacus quis magna. Curabitur imperdiet sapien libero, fringilla ullamcorper nibh ullamcorper vitae. Proin sed luctus augue.
  field_thumbnail:
    - entity: media
      bundle: image
      name: 'Product 3'
      status: 1
      field_image:
        - '#process':
            callback: 'file'
            args:
              - 'image'
              - type: 'module'
                filename: 'blue.png'
            alt: 'product3'
  field_product_media:
    - entity: media
      bundle: image
      name: 'Product 3'
      status: 1
      field_image:
        - '#process':
            callback: 'file'
            args:
              - 'image'
              - type: 'module'
                filename: 'blue.png'
            alt: 'product3'
    - entity: media
      bundle: image
      name: 'Product 3b'
      status: 1
      field_image:
        - '#process':
            callback: 'file'
            args:
              - 'image'
              - type: 'module'
                filename: 'blue.jpg'
            alt: 'product3b'
    - entity: media
      bundle: image
      name: 'Product 3c'
      status: 1
      field_image:
        - '#process':
            callback: 'file'
            args:
              - 'image'
              - type: 'module'
                filename: 'blue.png'
            alt: 'product3c'
  field_product_desc:
    - format: "full_html"
      summary: ''
      value: |
        <p>Point of sale (likewise called POS or checkout) is the spot where a retail exchange is finished. It is the point at which a client makes an installment to the shipper in return for merchandise or administrations. At the point of sale the retailer would ascertain the sum owed by the client and give alternatives to the client to make installment. The trader will likewise typically issue a receipt for the exchange. Point of Sales outsourcing is the best way to generate benefits.</p>
        <p>The POS software in different retail businesses uses altered equipment and software according to their necessities. Retailers may use measuring scales, scanners, electronic and manual money registers, EFTPOS terminals, touch screens and some other wide assortment of equipment and software accessible for utilization with POS. Case in point, a basic supply or confection store utilizes a scale at the point of sale, while bars and restaurants use POS system to alter the thing or administration sold when a client has an unique dinner or beverage demand.</p>
  field_link:
    - uri: 'http://google.com/'
      title: 'Contact us'
  field_content:
    - entity: paragraph
      type: text
      field_body:
        - format: "full_html"
          summary: ''
          value: |
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, turpis at luctus finibus, erat lectus convallis velit, at sodales purus lacus quis magna. Curabitur imperdiet sapien libero, fringilla ullamcorper nibh ullamcorper vitae. Proin sed luctus augue. Nam fringilla enim leo, non sodales ante gravida ac.</p>
            <p>Maecenas rhoncus, mi varius interdum euismod, odio velit bibendum libero, et cursus lectus sem quis sem. Quisque eget mauris accumsan, sollicitudin turpis at, mollis tellus. Vivamus scelerisque mauris eget enim dapibus fringilla. Aliquam erat volutpat. Aenean tincidunt scelerisque tortor vitae pellentesque. Suspendisse imperdiet suscipit arcu, vel posuere mauris fermentum at. Suspendisse potenti. Sed at fermentum odio. Aliquam condimentum consectetur eleifend. Nullam mollis ac tellus sit amet convallis. Donec consectetur pretium sapien a dictum. Aliquam ut erat ac nibh tempor interdum ac ut nisi.</p>
    - entity: paragraph
      type: media
      field_media:
        - entity: media
          bundle: video
          name: 'POS'
          status: 1
          field_media_video_embed_field:
            - value: 'https://www.youtube.com/watch?v=D3uwIww7flw'
    - entity: paragraph
      type: text
      field_body:
        - format: "full_html"
          summary: ''
          value: |
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, turpis at luctus finibus, erat lectus convallis velit, at sodales purus lacus quis magna. Curabitur imperdiet sapien libero, fringilla ullamcorper nibh ullamcorper vitae. Proin sed luctus augue. Nam fringilla enim leo, non sodales ante gravida ac.</p>
            <p>Maecenas rhoncus, mi varius interdum euismod, odio velit bibendum libero, et cursus lectus sem quis sem. Quisque eget mauris accumsan, sollicitudin turpis at, mollis tellus. Vivamus scelerisque mauris eget enim dapibus fringilla. Aliquam erat volutpat. Aenean tincidunt scelerisque tortor vitae pellentesque. Suspendisse imperdiet suscipit arcu, vel posuere mauris fermentum at. Suspendisse potenti. Sed at fermentum odio. Aliquam condimentum consectetur eleifend. Nullam mollis ac tellus sit amet convallis. Donec consectetur pretium sapien a dictum. Aliquam ut erat ac nibh tempor interdum ac ut nisi.</p>
    - entity: paragraph
      type: view
      field_view_ref:
        - target_id: 'related_products'
          display_id: 'block_1'
          title: 1
